<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0GKVC58" failures="1" tests="1" name="Test(failed)" time="11.015" errors="0" timestamp="2023-10-02T11:39:29 IST">
  <testcase classname="com.int_banking_testCases.TC_LoginTest_001" name="loginTest" time="2.044">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.int_banking_testCases.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:38)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test(failed) -->
